"""initial schema

Revision ID: a7b9b5b01750
Revises: 
Create Date: 2026-03-10 00:17:49.351134

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7b9b5b01750'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_service_requests_id'), table_name='service_requests')
    op.drop_index(op.f('ix_service_requests_tenant_id'), table_name='service_requests')
    op.drop_table('service_requests')
    op.drop_index(op.f('ix_dispatch_jobs_driver_id'), table_name='dispatch_jobs')
    op.drop_index(op.f('ix_dispatch_jobs_id'), table_name='dispatch_jobs')
    op.drop_index(op.f('ix_dispatch_jobs_service_request_id'), table_name='dispatch_jobs')
    op.drop_index(op.f('ix_dispatch_jobs_tenant_id'), table_name='dispatch_jobs')
    op.drop_table('dispatch_jobs')
    op.drop_index(op.f('ix_drivers_id'), table_name='drivers')
    op.drop_index(op.f('ix_drivers_tenant_id'), table_name='drivers')
    op.drop_table('drivers')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drivers',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('tenant_id', sa.VARCHAR(length=100), nullable=True),
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('phone', sa.VARCHAR(length=50), nullable=True),
    sa.Column('truck_number', sa.VARCHAR(length=50), nullable=True),
    sa.Column('vehicle_type', sa.VARCHAR(length=100), nullable=True),
    sa.Column('current_latitude', sa.FLOAT(), nullable=True),
    sa.Column('current_longitude', sa.FLOAT(), nullable=True),
    sa.Column('is_available', sa.BOOLEAN(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_drivers_tenant_id'), 'drivers', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_drivers_id'), 'drivers', ['id'], unique=False)
    op.create_table('dispatch_jobs',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('tenant_id', sa.VARCHAR(length=100), nullable=True),
    sa.Column('service_request_id', sa.INTEGER(), nullable=False),
    sa.Column('driver_id', sa.INTEGER(), nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), nullable=False),
    sa.Column('estimated_distance_miles', sa.FLOAT(), nullable=True),
    sa.Column('estimated_eta_minutes', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ),
    sa.ForeignKeyConstraint(['service_request_id'], ['service_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dispatch_jobs_tenant_id'), 'dispatch_jobs', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_dispatch_jobs_service_request_id'), 'dispatch_jobs', ['service_request_id'], unique=False)
    op.create_index(op.f('ix_dispatch_jobs_id'), 'dispatch_jobs', ['id'], unique=False)
    op.create_index(op.f('ix_dispatch_jobs_driver_id'), 'dispatch_jobs', ['driver_id'], unique=False)
    op.create_table('service_requests',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('tenant_id', sa.VARCHAR(length=100), nullable=True),
    sa.Column('customer_name', sa.VARCHAR(length=255), nullable=True),
    sa.Column('phone', sa.VARCHAR(length=50), nullable=True),
    sa.Column('location', sa.VARCHAR(length=500), nullable=False),
    sa.Column('formatted_address', sa.VARCHAR(length=500), nullable=True),
    sa.Column('latitude', sa.FLOAT(), nullable=True),
    sa.Column('longitude', sa.FLOAT(), nullable=True),
    sa.Column('place_id', sa.VARCHAR(length=255), nullable=True),
    sa.Column('vehicle_type', sa.VARCHAR(length=100), nullable=True),
    sa.Column('issue', sa.TEXT(), nullable=False),
    sa.Column('status', sa.VARCHAR(length=50), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_service_requests_tenant_id'), 'service_requests', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_service_requests_id'), 'service_requests', ['id'], unique=False)
    # ### end Alembic commands ###
